### PR TITLE
Fix: Completion being called consecutively

### LINKED ISSUE #29: Validate completion executes more than once; every 120 seconds.
I call `validate(on: view, completion: completion)`.  If I sit there (pretend the user is slow/reading something) the completion continuously calls about every 120 seconds, or, eventually the captcha dialog (img selection) shows up.  

ReCaptcha v1.1

### PR DESCRIPTION
**Pull request by fjcaetano**
fix #29

### CODE REVIEW

**Comment by MaximusMcCann** [comment]
Approved from my point of view.  Perhaps just switch off the JS logging if you weren't going to already.  Cheers!

**Comment by MaximusMcCann** [comment]
@fjcaetano could we tag v1.2 (or w/e) and update the podspec that has these updates please :)

**Comment by fjcaetano** [comment]
There are a few thing's I'd like to change before releasing this.

Meanwhile, I recommend you to point to the current HEAD commit on master and I'll ping you when I release the new version.

**Comment by MaximusMcCann** [comment]
cheers @fjcaetano

**Pull request merged**
