### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by SandroMachado**
This PR adds Carthage support.

### CODE REVIEW

**Comment by fjcaetano** [comment]
Hey @SandroMachado, you did the outstanding feat of being exactly one day late 😆 

Could you take a look at the branch `feature/carthage` and check if that works for you? Take a look at the README because there will be two generated frameworks. One for the core and one for the RxSwift extension.

It may be interesting to change the target branch in this PR to be `feature/carthage` one so we can review it better.

**Comment by SandroMachado** [comment]
Too late! :)

@fjcaetano can you please downgrade the deploy target to iOS 8? or iOS 9?

I am trying to use your branch but the deploy target is 10.3.

https://github.com/fjcaetano/ReCaptcha/blob/feature/carthage/ReCaptcha-Carthage.xcodeproj/project.pbxproj#L379

**Comment by fjcaetano** [comment]
Sure, it probably slipped me when I was creating the target

**Comment by SandroMachado** [comment]
Great! 👍 

Thanks

**Pull request closed without merging**
