### PR TITLE
Change Rx dependencies version from '~> 4.3.1' to '~> 4.3'

### LINKED ISSUE #58: Change version of RxSwift dependency in podspec
Hello,
We are migrating our project from Swift 4.1 to Swift 4.2.
The project and all its dependencies (except ReCaptcha) are using RxSwift 4.4.0. The problem is ReCaptcha 1.4 can not use version 4.4.0 of RxSwift because of `rx.dependency 'RxSwift', '~> 4.3.1'`
May it be replaced with e.g. `rx.dependency 'RxSwift', '~> 4.3'`? (ReCaptcha has no conflicts with RxSwift 4.4.0)

Please let me know if I could make PR to update podspec file.

### PR DESCRIPTION
**Pull request by maxxx777**
Fix #58

### CODE REVIEW

**Comment by maxxx777** [comment]
@fjcaetano, regarding ci failure: 
- looks like `pod repo update` should be called on the travis to update RxSwift version.
- test__Validate__Show_ReCaptcha is randomly failed on my machine, even before PR's changes.

**Comment by fjcaetano** [comment]
Hey @maxxx777, don't worry about Travis, we'll fix it later. Meanwhile, have you checked if Carthage is working correctly? I'm asking this because you didn't change `Cartfile` and I'm checking if it really isn't needed.

**Comment by maxxx777** [comment]
@fjcaetano thanks for the note, completely forgot to check Carthage.
[Carthage documentation about versioning](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#version-requirement) confuses me a bit. But it looks like `carthage update` updates RxSwift to 4.4.0 even if Cartfile contains `github "ReactiveX/RxSwift" ~> 4.3.1`.
However, I did the updates in Cartfile to keep the same version of RxSwift dependency in both CocoaPods and Carthage.

**Comment by fjcaetano** [comment]
Release as version 1.4.1 🚀 

Congrats @maxxx777 🎉

**Comment by maxxx777** [comment]
@fjcaetano thank you!

**Pull request merged**
