### PR TITLE
Fixed wrong Domain retrieving.

### PR DESCRIPTION
**Pull request by mrahleev**

### CODE REVIEW

**Comment by fjcaetano** [comment]
@mrahleev thanks for this PR, but what issue does this fix? Also, how can I reproduce it?

**Comment by mrahleev** [comment]
@fjcaetano  As you can see, in case if there is no any value for Constants.InfoDictKeys.Domain key inside Info.plist, first check in guard will fail. And in this case second check with baseURL will never execute.

`guard let domain = infoDict?[Constants.InfoDictKeys.Domain] as? String, let baseURL = baseURL ?? URL(string: domain) else { ... }`

You can check it by removing ApiKey and Domain from Info.plist and then by using `Recaptcha(apiKey:baseURL:)` initialiser.

**Comment by fjcaetano** [comment]
Indeed. Could you also write some tests to cover that, please?

**Comment by mrahleev** [comment]
@fjcaetano Yes, I'll do some tests in free time.

**Comment by fjcaetano** [comment]
Thanks @mrahleev. Just two things to keep in mind:
1. Make sure the new tests fail without your fix
2. Make sure they pass with it

**Comment by fjcaetano** [comment]
@mrahleev any updates on these tests?

**Pull request merged**
