### PR TITLE
Swift4.0

### PR DESCRIPTION
**Pull request by wberger**
I have updated the current master branch to depend on RxSwift/RxCocoa 4 (alpha) and Swift 4. Furthermore I have updated the Example project to XCode 9 recommended settings.

However, I would recommend merging the request into a branch other than master, as the current version depends on alpha libraries.

### CODE REVIEW

**Comment by fjcaetano** [comment]
Thanks @wberger that is fantastic work. Quick question, the build settings changes are all the default for Swift 4, right?

**Comment by fjcaetano** [comment]
@wberger I've changed the base branch for this to be merged onto the `swift4` branches. Could you fix the Travis config so it passes the tests?

**Comment by wberger** [comment]
Thanks, I will check everything on Thursday!

**Comment by wberger** [comment]
I verified the build settings, it is a swift 4 build. Travis now uses Xcode 9. However, building RxSwift alpha seemingly produces two warnings which causes the Travis build to fail. I will check that tomorrow.

**Comment by fjcaetano** [comment]
@wberger Thank you very much for your changes. Don't sweat too much if you're having a hard time solving this. It'd be great to have it fixed, but since this won't be merged into the `master` branch yet, it's not too big of a deal to `--allow-warnings` in this branch.

**Pull request closed without merging**
