### PR TITLE
Updates to support Swift 4.2.

### PR DESCRIPTION
**Pull request by manderson420**
There are a few errors that are thrown when trying to compile against Swift 4.2 so I made some fixes. I doubt you want the changes to go in to target the Swift 4.2 version so let me know how to proceed with any changes necessary.

### CODE REVIEW

**Comment by fjcaetano** [comment]
Hi @manderson420 thanks for this update. Could you try and get the CI to pass the tests? It's probably just a matter of updating `osx_image` in the Travis CI config file.

**Comment by manderson420** [comment]
@fjcaetano It seems like `scan` is still building with an older xcode version `xcode_path             | /Applications/Xcode-9.4.1.app`. Seems like something you may need to fix on your end unless I missed something (I basically followed your previous commit for updating the osx_image). Silly question but will this break clients compiling with older versions of swift in their projects then? The swift 3 version -> 4.2 is quite a jump.

**Comment by fjcaetano** [comment]
The Travis build is still using Xcode 9.4.1, this is weird. I'll take a closer look.

And yes, those still using Swift 3 won't be able to upgrade to newer versions of ReCaptcha. They'll have to keep pointing to previous versions.

**Comment by manderson420** [comment]
> The Travis build is still using Xcode 9.4.1, this is weird. I'll take a closer look.

Ok, let me know what you are able to come up with.

> And yes, those still using Swift 3 won't be able to upgrade to newer versions of ReCaptcha. They'll have to keep pointing to previous versions.

Sounds good, just wanted to make sure you were ok with that before moving forward 👍

**Comment by manderson420** [comment]
@fjcaetano Any thoughts on a fix for this? I noticed another PR attempting to resolve the issue but it seems to be failing as well. Let me know if I can help.

**Comment by manderson420** [comment]
@fjcaetano We ended up having to make more updates than originally assumed. Please take a look and let me know if you have any issues with the changes. 

- The RxSwift version needed to be bumped in order to use the newest Swift 4.2 language features. 
- I bumped the fastlane version specified in the Gemfile.
- I bumped the cocoapods version in the Gemfile which changed some of the settings in the pbxproj file.

Everything should be good to go (as long as the travis build passes).

**Comment by fjcaetano** [comment]
Wow dude! That's awesome! I've not been able to give much attention to this project recently, so thanks for taking over this. I'll squash your commits and merge this PR as-is.

**Comment by fjcaetano** [comment]
Hey @manderson420, once again, thanks for your help. Since you've been quite active in this project, would you be interested in helping me manage this? I could use all the help I can get, from just replying to issues, all the way to implementing enhancements and deploying. What do you think?

**Pull request merged**
